{
 "title": "northwind",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "NORTHWIND SALES DASHBOARD", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Unit in stock per products",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 7, "x": 1, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT StockStatus , count(*)    FROM (SELECT \r\n    ProductName,\r\n    CategoryName,\r\n    units_in_stock,\r\n    units_on_order,\r\n    reorder_level,\r\n    CASE \r\n        WHEN units_in_stock <= reorder_level THEN 'Low Stock'\r\n        WHEN units_in_stock <= (reorder_level * 2) THEN 'Medium Stock'\r\n        ELSE 'Good Stock'\r\n    END AS StockStatus\r\nFROM DimProducts\r\nORDER BY units_in_stock ASC) GROUP BY StockStatus  ; "
    }
   ]
  },
  {
   "title": "Orders per shipper Company ",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n    ds.company_name AS ShipperCompany,\r\n    COUNT(DISTINCT fo.OrderAlternateKey) AS NumberOfOrders\r\nFROM FactOrders fo\r\nLEFT  JOIN DimShippers ds ON fo.ShipperKey = ds.ShipperKey\r\nGROUP BY ds.company_name\r\nORDER BY NumberOfOrders DESC;"
    }
   ]
  },
  {
   "title": "Number of customers ",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 2, "x": 14, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(distinct(CustomerAlternateKey)) FROM \"default\".\"DimCustomer\" "
    }
   ]
  },
  {
   "title": "Number of orders",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT  count()  FROM \"default\".\"FactOrders\" "
    }
   ]
  },
  {
   "title": "Number of products",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 2, "x": 21, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(distinct(ProductAlternateKey)) FROM \"default\".\"DimProducts\" "
    }
   ]
  },
  {
   "title": "Top 5 companies by sales ",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 9, "x": 14, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT \r\n    dc.CompanyName,\r\n    dc.ContactName,\r\n    SUM(fo.TotalAmount) AS TotalSales\r\nFROM FactOrders fo\r\nLEFT JOIN DimCustomer dc ON fo.CustomerKey = dc.CustomerKey\r\nGROUP BY dc.CompanyName, dc.ContactName\r\nORDER BY TotalSales DESC\r\nLIMIT 5;"
    }
   ]
  },
  {
   "title": "Total sales by month",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 13, "x": 1, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\r\n    toMonth(dd.`Date`) AS Month,\r\n    SUM(fo.TotalAmount) AS TotalSales\r\nFROM FactOrders fo\r\nLEFT JOIN DimDate dd\r\n    ON fo.OrderDate = dd.DateKey\r\nGROUP BY Month\r\nORDER BY Month ;\r\n\r\n"
    }
   ]
  },
  {
   "title": "Top country by sales",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 9, "x": 14, "y": 14 },
   "targets": [
    {
     "rawSql": "SELECT \r\n    dg.country,\r\n\r\n    SUM(fo.TotalAmount) AS TotalSales\r\n\r\n\r\nFROM FactOrders fo\r\nLEFT JOIN DimCustomer dc ON fo.CustomerKey = dc.CustomerKey\r\nLEFT JOIN DimGeography dg ON dc.GeographyKey = dg.GeographyKey\r\nGROUP BY dg.country\r\nORDER BY TotalSales DESC LIMIT 5;"
    }
   ]
  },
  {
   "title": "Top product  by sales",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 13, "x": 1, "y": 15 },
   "targets": [
    {
     "rawSql": "SELECT \r\n    dp.ProductName,\r\n    dp.CategoryName,\r\n    SUM(fo.TotalAmount) AS TotalSales\r\nFROM FactOrders fo\r\nLEFT JOIN DimProducts dp ON fo.ProductKey = dp.ProductKey\r\nGROUP BY dp.ProductName, dp.CategoryName\r\nORDER BY TotalSales DESC\r\nLIMIT 7;"
    }
   ]
  }
 ]
}