{
 "title": "northwind",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Top 5 companies by sales ",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \r\n    dc.CompanyName,\r\n    dc.ContactName,\r\n    SUM(fo.TotalAmount) AS TotalSales\r\nFROM FactOrders fo\r\nINNER JOIN DimCustomer dc ON fo.CustomerKey = dc.CustomerKey\r\nGROUP BY dc.CompanyName, dc.ContactName\r\nORDER BY TotalSales DESC\r\nLIMIT 5;"
    }
   ]
  },
  {
   "title": "Orders per shipper Company ",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 7, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n    ds.company_name AS ShipperCompany,\r\n    COUNT(DISTINCT fo.OrderAlternateKey) AS NumberOfOrders\r\nFROM FactOrders fo\r\nINNER JOIN DimShippers ds ON fo.ShipperKey = ds.ShipperKey\r\nGROUP BY ds.company_name\r\nORDER BY NumberOfOrders DESC;"
    }
   ]
  },
  {
   "title": "Number of products",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(*) FROM \"default\".\"DimProducts\" "
    }
   ]
  },
  {
   "title": "Number of orders",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT  count()  FROM \"default\".\"FactOrders\" "
    }
   ]
  },
  {
   "title": "Number of customers ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 16, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(*) FROM \"default\".\"DimCustomer\" "
    }
   ]
  },
  {
   "title": "Unit in stock per products",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT StockStatus , count(*)    FROM (SELECT \r\n    ProductName,\r\n    CategoryName,\r\n    units_in_stock,\r\n    units_on_order,\r\n    reorder_level,\r\n    CASE \r\n        WHEN units_in_stock <= reorder_level THEN 'Low Stock'\r\n        WHEN units_in_stock <= (reorder_level * 2) THEN 'Medium Stock'\r\n        ELSE 'Good Stock'\r\n    END AS StockStatus\r\nFROM DimProducts\r\nORDER BY units_in_stock ASC) GROUP BY StockStatus  ; "
    }
   ]
  },
  {
   "title": "top 10 products by sales ",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT \r\n    dp.ProductName,\r\n    dp.CategoryName,\r\n    SUM(fo.TotalAmount) AS TotalSales\r\nFROM FactOrders fo\r\nINNER JOIN DimProducts dp ON fo.ProductKey = dp.ProductKey\r\nGROUP BY dp.ProductName, dp.CategoryName\r\nORDER BY TotalSales DESC\r\nLIMIT 10;"
    }
   ]
  },
  {
   "title": "New panel",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT \r\n    dg.country,\r\n\r\n    SUM(fo.TotalAmount) AS TotalSales\r\n\r\n\r\nFROM FactOrders fo\r\nINNER JOIN DimCustomer dc ON fo.CustomerKey = dc.CustomerKey\r\nINNER JOIN DimGeography dg ON dc.GeographyKey = dg.GeographyKey\r\nGROUP BY dg.country\r\nORDER BY TotalSales DESC LIMIT 15;"
    }
   ]
  }
 ]
}